spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/academia}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
